[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    miguelbalboa/MFRC522@^1.4.11
    bblanchon/ArduinoJson@^7.0.0
    olikraus/U8g2@^2.35.0
    ricmoo/QRCode@^0.0.1
build_flags =
    -D CORE_DEBUG_LEVEL=0
build_src_filter = +<main.cpp> +<config.h> +<secrets.h> -<rc522_test.cpp>

[env:oled_test]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.35.0
build_flags =
    -D CORE_DEBUG_LEVEL=0
build_src_filter = +<oled_test.cpp> +<config.h> -<main.cpp>

; [env:rc522_test]
; platform = espressif8266
; board = nodemcuv2
; framework = arduino
; monitor_speed = 115200
; lib_deps =
;     miguelbalboa/MFRC522@^1.4.11
; build_flags =
;     -D CORE_DEBUG_LEVEL=0
; build_src_filter = +<rc522_test.cpp> -<main.cpp>